version: '3.8'

services:
  db:
    image: postgres
    container_name: 'estufa-db'
    environment:
      - POSTGRES_DB=estufa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '7432:5432'

  redis:
    image: redis:alpine
    container_name: 'estufa-redis'
    ports:
      - '6379:6379'
